version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    expose:
      - '6379'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - '27017'
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:     
